FROM postgres:latest

# Set environment variables
ENV POSTGRES_USER tahakhan
ENV POSTGRES_DB billing_app_db

# Run a script to update the pg_hba.conf file
COPY update_pg_hba.sh /docker-entrypoint-initdb.d/

# Make the script executable
RUN chmod +x /docker-entrypoint-initdb.d/update_pg_hba.sh
